version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_DATASOURCE_PASSWORD_DRIVER_CLASS_NAME: org.postgresql.Driver